### ISSUE TITLE
Error creating new wiki as a User with a standard role.

### ISSUE THREAD

**Issue by barnes7td** [divyasripadham/blocipedia#1]
Context: Standard User on New Wikis View, form filled out.
Action: Clicked the Submit button
Result: Error

<img width="1122" alt="screen shot 2016-01-23 at 11 56 51 pm" src="https://cloud.githubusercontent.com/assets/382636/12534609/a8b9e89a-c22f-11e5-9237-3b21821f2760.png">

Factors: 
1. This would best be tested with a feature spec, but we haven’t gone over that.
2. Without test coverage and adding collaborator code, error was created.
3. This is fixed in the #update method.

**Comment by divyasripadham** [comment]
Fixed the error

https://github.com/divyasripadham/blocipedia/commit/f22be68c202a227a2a05f79a121e40a7d893e33a

**Comment by barnes7td** [comment]
Approved.
