### ISSUE TITLE
There is no seed data that creates premium or admin users.

### ISSUE THREAD

**Issue by barnes7td** [divyasripadham/blocipedia#2]
Context: As a Developer, I tried to sign in as an Premium User.
Action: Looked in the seed.rb file for the seeded premium users creds.
Result: No user has been seeded as premium. Sending back to dev to create.

This is a blocker! I can't test out the rest of the features until, seed data is created!

**Comment by divyasripadham** [comment]
Added seed data

https://github.com/divyasripadham/blocipedia/commit/f22be68c202a227a2a05f79a121e40a7d893e33a

**Comment by barnes7td** [comment]
This would have been better as 2 separate commits. 

Approved.
